repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: 2.1.3
    hooks:
    -   id: pyproject-fmt

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
    -   id: ruff
        args: [ --fix ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
     -  id: mypy
        args: [--strict]
        files: bot/
        additional_dependencies: [uvloop, aiogram, aiogram_i18n, pydantic-settings, sqlalchemy, redis, pytest]
