services:
   redis:
      image: redis:alpine
      restart: on-failure
      volumes:
         - redis-data:/redis_data

   db:
      image: postgres:alpine
      restart: on-failure
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${DB__PASSWORD}
         POSTGRES_USER: ${DB__USER}
         POSTGRES_DB: ${DB__DB}
      volumes:
         - db-data:/var/lib/postgresql/data

   bot:
      image: bagoont/nc_tg_bot
      restart: always
      env_file: .env
      depends_on:
         - redis
         - db
volumes:
   redis-data:
   db-data:
   nc-data:
