services:
   redis:
      image: redis:alpine
      env_file: .env
      restart: on-failure

   db:
      image: postgres:alpine
      restart: on-failure
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_USER: ${DB_USER}
         POSTGRES_DB: ${DB_DB}
      volumes:
         - db-data:/var/lib/postgresql/data

   bot:
      build: .
      restart: always
      env_file: .env
      depends_on:
         - redis
         - db
volumes:
   db-data:
   nextcloud:
