services:
   nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nc-data:/var/www/html

   redis:
      image: redis:alpine
      restart: on-failure
      volumes:
         - redis-data:/redis_data

   db:
      image: postgres:alpine
      restart: on-failure
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${DB__PASSWORD}
         POSTGRES_USER: ${DB__USER}
         POSTGRES_DB: ${DB__DB}
      volumes:
         - db-data:/var/lib/postgresql/data

   bot:
      build: .
      restart: always
      env_file: .env
      depends_on:
         - redis
         - db
volumes:
   redis-data:
   db-data:
   nc-data:
