name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        Please paste or describe the expected results.
      placeholder: >
        Example: No error is thrown.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: |
        Please paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full traceback** of the exception.
      placeholder: >
        Please paste or specifically describe the actual output or traceback.
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Setup configuration
      description: |
        Paste or describe the configuration setting, including software versions, to help diagnose the problem more quickly.
      placeholder: >
        Example: nextcloud = 28.0.4, etc.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!
