blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/blvdek/nc_tg_bot/discussions/new
    about: Please ask and answer questions here.
  - name: Security
    url: https://github.com/blvdek/nc_tg_bot/security/advisories/new
    about: Please report security vulnerabilities here.
